(() => {
"use strict";
const c=document.getElementById("game"),x=c.getContext("2d"),hp=document.getElementById("hp"),bar=document.getElementById("hpbar"),msg=document.getElementById("message");
const W=c.width,H=c.height,A={x:170,y:105,w:620,h:330},keys=new Set();
let p,k,bs,ps,state,t0=0;
const img=new Image();img.src="./assets/sprites/enemies/knight/knight%20idle/spr_roaringknight_idle.png";
function reset(){p={x:480,y:385,r:9,hp:100,cd:0,inv:0};k={x:480,y:190,hp:100,t:0,atk:1};bs=[];ps=[];state="fight";msg.textContent="Move with WASD or arrow keys. Press SPACE to attack.";hud()}
function hud(){hp.textContent=Math.ceil(p.hp)+" / 100";bar.style.width=p.hp+"%"}
function shoot(a,s=170){bs.push({x:k.x,y:k.y+30,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:5,l:5})}
function burst(X,Y,n=8){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=30+Math.random()*100;ps.push({x:X,y:Y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:.5})}}
function attack(){if(state!=="fight"||p.cd>0)return;p.cd=.4;if(Math.hypot(p.x-k.x,p.y-k.y)<105){k.hp=Math.max(0,k.hp-8);burst(k.x,k.y,12);if(!k.hp){state="win";msg.textContent="VICTORY. PRESS R TO FIGHT AGAIN."}}}
function update(dt){if(state!=="fight")return;p.cd=Math.max(0,p.cd-dt);p.inv=Math.max(0,p.inv-dt);k.t+=dt;k.atk-=dt;let dx=0,dy=0;if(keys.has("a")||keys.has("arrowleft"))dx--;if(keys.has("d")||keys.has("arrowright"))dx++;if(keys.has("w")||keys.has("arrowup"))dy--;if(keys.has("s")||keys.has("arrowdown"))dy++;if(dx||dy){let m=Math.hypot(dx,dy);p.x=Math.max(A.x+12,Math.min(A.x+A.w-12,p.x+dx/m*230*dt));p.y=Math.max(A.y+18,Math.min(A.y+A.h-12,p.y+dy/m*230*dt))}
if(k.atk<=0){k.atk=1.1;let a=Math.atan2(p.y-k.y,p.x-k.x),m=Math.floor(Math.random()*3);if(m===0){for(let i=-1;i<=1;i++)shoot(Math.PI/2+i*.16,150)}else if(m===1){shoot(a,190);shoot(a-.2,170);shoot(a+.2,170)}else for(let i=0;i<10;i++)shoot(Math.PI*2*i/10+k.t,105);burst(k.x,k.y,4)}
for(let i=bs.length-1;i>=0;i--){let b=bs[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.l-=dt;if(Math.hypot(b.x-p.x,b.y-p.y)<b.r+p.r&&p.inv<=0){p.hp=Math.max(0,p.hp-7);p.inv=.5;burst(p.x,p.y,6);if(!p.hp){state="lose";msg.textContent="GAME OVER. PRESS R TO TRY AGAIN."}bs.splice(i,1);continue}if(b.l<=0||b.x<0||b.x>W||b.y<0||b.y>H)bs.splice(i,1)}
for(let i=ps.length-1;i>=0;i--){let q=ps[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.97;q.vy*=.97;q.l-=dt;if(q.l<=0)ps.splice(i,1)}hud()}
function draw(){x.fillStyle="#030303";x.fillRect(0,0,W,H);x.strokeStyle="#222";for(let X=A.x;X<=A.x+A.w;X+=40){x.beginPath();x.moveTo(X,A.y);x.lineTo(X,A.y+A.h);x.stroke()}for(let Y=A.y;Y<=A.y+A.h;Y+=40){x.beginPath();x.moveTo(A.x,Y);x.lineTo(A.x+A.w,Y);x.stroke()}x.strokeStyle="#aaa";x.strokeRect(A.x,A.y,A.w,A.h);let bob=Math.sin(k.t*2)*5;if(img.complete&&img.naturalWidth){x.save();x.imageSmoothingEnabled=false;x.globalAlpha=.16;x.drawImage(img,k.x-20,k.y-15+bob,70,70);x.globalAlpha=1;x.drawImage(img,k.x-55,k.y-55+bob,110,110);x.restore()}else{x.fillStyle="#ddd";x.fillRect(k.x-24,k.y-32+bob,48,64)}x.fillStyle="#fff";x.font="bold 13px monospace";x.textAlign="center";x.fillText("ROARING KNIGHT",k.x,k.y-65+bob);x.fillStyle="#222";x.fillRect(k.x-60,k.y-53+bob,120,5);x.fillStyle="#ddd";x.fillRect(k.x-60,k.y-53+bob,120*k.hp/100,5);for(const b of bs){x.beginPath();x.fillStyle="#eee";x.arc(b.x,b.y,b.r,0,7);x.fill()}for(const q of ps){x.globalAlpha=Math.max(0,q.l*2);x.fillStyle="#fff";x.fillRect(q.x-2,q.y-2,4,4)}x.globalAlpha=1;x.beginPath();x.fillStyle=p.inv>0?"#777":"#fff";x.arc(p.x,p.y,p.r,0,7);x.fill();if(state!=="fight"){x.fillStyle="rgba(0,0,0,.72)";x.fillRect(0,0,W,H);x.fillStyle="#fff";x.font="bold 54px Impact,Arial";x.fillText(state==="win"?"VICTORY":"GAME OVER",W/2,H/2)}}
function loop(t){let dt=Math.min((t-t0)/1000||0,.033);t0=t;update(dt);draw();requestAnimationFrame(loop)}
addEventListener("keydown",e=>{let q=e.key.toLowerCase();if(q===" "||q.startsWith("arrow"))e.preventDefault();keys.add(q);if(q===" ")attack();if(q==="r")reset()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));reset();requestAnimationFrame(loop)
})();